apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebapp
        image: vgvdocker2694/java-docker-demo:$BUILD_ID
        ports:
        - name: javawebapp
          containerPort: 8080  
---
# Load Balncer
apiVersion: v1
kind: Service
metadata:
  name: javawebapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: javawebapp
