---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-webapp
  labels:
    app: java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: javawebapp
        image: vgvdocker2694/java-docker-demo:$BUILD_ID
        ports:
        - containerPort: 8080
  
---
# Load Balncer
apiVersion: v1
kind: Service
metadata:
  name: java-lb
spec:
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
  
