---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-webapp
  template:
    metadata:
      labels:
        app: java-webapp
    spec:
      containers:
        - name: java-webapp
          image: vgvdocker2694/java-docker-demo:$BUILD_ID
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"  
---
# Load Balncer
apiVersion: v1
kind: Service
metadata:
  name: java-webapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: java-webapp
      targetPort: 8080
   type: LoadBalancer   
  
